name: build
on: push
jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-pandoc@v1
      with:
        pandoc-version: '2.7.3'

    - run: ./bin/build