name: build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  job1:
    name: Build docs
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
          node-version: 12.x
    - uses: r-lib/actions/setup-pandoc@v1
      with:
        pandoc-version: '2.7.3'
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
        bundler-cache: true

    - run: ./bin/build
    - uses: actions/checkout@v2
      if: ${{ contains(github.event.pull_request.labels.*.name, 'build:jsdocs') }}
      with:
        repository: handshake-org/hsd
        path: hsd
    - name: Build JSDocs
      if: ${{ contains(github.event.pull_request.labels.*.name, 'build:jsdocs') }}
      run: |
        cd hsd
        npm install -g jsdoc
        jsdoc -c jsdoc.json
        cp -r ./docs/reference ../build/docs
    - name: Deploy
      if: github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        cname: hsd-dev.org