name: build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  job1:
    name: Build docs
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-pandoc@v1
      with:
        pandoc-version: '2.7.3'
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
        bundler-cache: true

    - run: ./bin/build
    # Temporary disabled. See #545 on handshake-org/hsd
    # - uses: actions/checkout@v2
    #   with:
    #     repository: handshake-org/hsd
    #     ref: master
    #     path: hsd
    # - run: |
    #     cd hsd
    #     npm i -D jsdoc
    #     node node_modules/.bin/jsdoc -c jsdoc.json
    #     cp -r ./docs/reference ../build/docs
    - name: Deploy
      if: github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        keep_files: true  # this will keep the old jsdocs while handshake-org/hsd/pull/545 is not merged
        cname: hsd-dev.org