name: build
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.files.outputs.matrix }}

    steps:
    - uses: actions/checkout@v2
    - name: Files
      id: files
      run: |
          mkdir -p ./{install,guides}

          arr=""
          for file in ./src/*.md
          do
            arr='"'$(basename "$file" | cut -d. -f1)'",'$arr
          done
          src=$(echo $arr | cut -d. -f1)

          arr=""
          for file in ./src/guides/*.md
          do
            arr='"'$(basename "$file" | cut -d. -f1)'",'$arr
          done
          guides=$(echo $arr | cut -d. -f1)
          echo "::set-output name=matrix::{\"src\":[$src],\"guides\":[$guides]}"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.job1.outputs.matrix).src}}
    steps:
    - uses: docker://pandoc/latex:2.9
      with:
        args: ./src/${{ matrix.src }}.md -T ${{ matrix.src }} -V "active-${{ matrix.src }}:true" -V "ghpath:${{ matrix.src }}" -V "pagetitle:${{ matrix.src }}" -w html5 -o "${{ matrix.src }}.html" --template ./src/templates/layout.html