name: build
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.files.outputs.src }}
      guides: ${{ steps.files.outputs.guides }}

    steps:
    - uses: actions/checkout@v2
    - name: Files
      id: files
      run: |
          mkdir -p ./{install,guides}

          arr=""
          for file in ./src/*.md
          do
            arr='"'$(basename "$file" | cut -d. -f1)'",'$arr
          done
          src=$(echo $arr | cut -d. -f1)

          arr=""
          for file in ./src/guides/*.md
          do
            arr='"'$(basename "$file" | cut -d. -f1)'",'$arr
          done
          guides=$(echo $arr | cut -d. -f1)
          echo "::set-output name=src::{\"file\":[$src]}"
          echo "::set-output name=guides::{\"file\":[$guides]}"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.job1.outputs.src)}}
    steps:
    - uses: docker://pandoc/latex:2.9
      with:
        args: ./src/${{ matrix.file }}.md -T ${{ matrix.file }} -V "active-${{ matrix.file }}:true" -V "ghpath:${{ matrix.file }}" -V "pagetitle:${{ matrix.file }}" -w html5 -o "${{ matrix.file }}.html" --template ./src/templates/layout.html